dashboards/eigenda-metrics.json, docker-compose.yml, resources/rate-limit-nginx.conf
- nginx remove disperses
- update one DA graph.
=> remove disperser nginx

.env, run.sh
Node: ghcr.io/layr-labs/eigenda/opr-node:release-0.1.1
Node Plugin: ghcr.io/layr-labs/eigenda/opr-nodeplugin:release-0.1.1
EigenDA release notes: https://github.com/Layr-Labs/eigenda/releases/tag/v0.1.1
This is an optional but recommended upgrade.
=> [upgrade] node and nodeplugin images

README.md
=> sync readme

monitoring/README.md
replace `docker-compose` with `docker compose`
=> remove old docker compose cmd

run.sh
- We want to remove docker container for the image used for opt-in and out
=> remove container after execution

.env
change `PUBLIC_IP_CHECK_INTERVAL` --> `NODE_PUBLIC_IP_CHECK_INTERVAL`
=> fix env var `NODE_PUBLIC_IP_CHECK_INTERVAL`

run.sh
=> update plugin image

README.md
- Add details for upgrade to make sure TODOs are still correct
=> add more details for upgrade

.env, run.sh
Optional but recommended
https://github.com/Layr-Labs/eigenda/releases/tag/v0.2.1
=> release eigenda v0.2.1

.env.example, run.sh
EigenDA release v0.2.2 - https://github.com/Layr-Labs/eigenda/releases/tag/v0.2.2
=> release 0.2.2

.env.example, run.sh
Release Notes: https://github.com/Layr-Labs/eigenda/releases/tag/v0.2.3
=> release 0.2.3

README.md, run.sh
=> add update quorum

.env.example, run.sh
=> release 0.4.0

goerli/.env.example
Updates the logger config as updated in https://github.com/Layr-Labs/eigenda/pull/323 and https://github.com/Layr-Labs/eigenda/pull/331
=> Update node logger config

goerli/README.md, goerli/run.sh
corresponding to https://github.com/Layr-Labs/eigenda/pull/362
=> Remove update-quorums

holesky/.env.example, holesky/README.md, holesky/docker-compose.yml, holesky/run.sh, monitoring/README.md, monitoring/prometheus.yml
1. Copy goerli to holesky
2. update goerli references to holesky
3. minor changes to monitoring readme
=> [Holesky] Add Setup

holesky/README.md
We revamped the EigenDA operator CLI. This PR updates the opt-in/opt-out documentation.
=> Update revamped opt-in/opt-out CLI semantics

monitoring/alerting/eigenda-alerts.json
=> Replaced goerli link for holesky in eigenda-alerts.json

holesky/run.sh
=>  some fixes

holesky/.env.example, holesky/run.sh, mainnet/.env.example, mainnet/run.sh
- release v0.6.1
- improve shell ux
=> release v0.6.1

monitoring/README.md, monitoring/dashboards/eigenda-metrics.json
=> Revamp eigenda metrics dash to highlight batch counts to help users gauge reachability and health

monitoring/dashboards/eigenda-metrics.json
=> Add node down/unreachable warning when no data found

holesky/run.sh, mainnet/run.sh
- support update socket
- Do not merge till new eigenda release
=> [Holesky] support update socket

holesky/.env.example, holesky/run.sh, mainnet/.env.example, mainnet/run.sh
=> update mainnet node version to 0.6.2

monitoring/dashboards/eigenda-metrics.json
- Change graph title to reflect that Rank is by TVL
=> clarify graph title

holesky/.env.example, holesky/run.sh, mainnet/.env.example, mainnet/run.sh
please review and merge. I do not have the permission to merge
=> update mainnet image to 0.8.5

README.md, mainnet-beta/README.md
=> Add more info to mainnet-beta socket registration
